source 'https://rubygems.org'
ruby '3.2.2'

gem 'rails', '~> 7.1.3'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'

# API
gem 'rack-cors'
gem 'jbuilder'
gem 'jsonapi-serializer'

# Auth
gem 'jwt'
gem 'bcrypt'

# HTTP client (Chatwoot API)
gem 'faraday'
gem 'faraday-retry'

# Background jobs
gem 'sidekiq', '~> 7.2'
gem 'redis', '~> 5.0'

# Storage (attachments)
gem 'aws-sdk-s3', require: false

# Utils
gem 'acts_as_list'
gem 'friendly_id', '~> 5.5'
gem 'kaminari'
gem 'bootsnap', require: false

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rubocop', require: false
end

group :development do
  gem 'listen'
  gem 'spring'
end
